name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/mm-apm-1351-aws-build-agents
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    test_steps:
      - bash: |
          set -e
          make test-report
        displayName: run tests
        workingDirectory: "${{ variables.service_name }}"
      - bash: |
          if [ ! -f "reports/tests/async-slowapp.xml" ]; then
            echo "no test results found"
            exit -1
          fi
        workingDirectory: ${{ variables.service_name }}
        displayName: 'check test results exist'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "${{ variables.service_name }}/reports/tests/*.xml"
          failTaskOnFailedTests: true
        displayName: publish test report

