# .github/workflows/sbom.yml
name: SBOM Check

on:
  workflow_dispatch:
    inputs:
      run:
        description: "Run SBOM check"
        required: true
        type: boolean
        default: true

jobs:
  sbom:
    if: ${{ inputs.run }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write  # needed if you want SBOMs uploaded to Releases
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: "1.12.2"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@ae78205cfffec9e8d93fd2b3115c7e9d3166d4b6

      # Base SBOM for repo (SPDX JSON). Also uploaded as a workflow artifact.
      - name: Generate SBOM (repo)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json